#base image
FROM python:3.10


# working directory
WORKDIR /flask_app

# copy
COPY . /flask_app

# run
RUN pip install -r requirements.txt

#port
EXPOSE 5000

## command
CMD ["python", "./flask_app.py"]